title: Jekyll theme ASCII
author:

show_excerpts: false

external_theme: antoniovazquezblanco/jekyll-theme-ascii
  name: Antonio Vázquez Blanco
description: This is a simple Jekyll theme that relies mostly on ASCII characters. And maybe emojis :).

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
 - index.md
 - about.md
