title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false

theme: jekyll-theme-ascii

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
 - index.md
 - about.md
